GET http://localhost:3030/api/portafolios/1


### test de posts proyectos
POST http://localhost:3030/api/proyectos/
Content-Type: application/json

{
    "title": "proyecto de prueba",
    "description": "api rest test",
    "portafolioId": 1,
    "imgproject": "https://my-cara.com"
}

### Test post correo
POST http://localhost:3030/api/portafolios/email
Content-Type: application/json

{
    "nombre": "Remitente",
    "email": "fueleme@gmail.com",
    "asunto": "Probar el controlador",
    "mensaje": "Mensaje de prueba",
    "userName":"Festy",
    "emailUser": "fueleme@gmail.com"
    

}

### Envio de portafolio
POST http://localhost:3030/api/portafolios/
Content-Type: application/json

{
    "imgUser": "https://my-cara.com",
    "skills": "muy bueno en js",
    "achievements": "api en express",
    "userId": 1
}
### Test enpoint put
PUT  http://localhost:3030/api/contactos/1
Content-Type: application/json

{
    "id": 1,
	"telefono": "8888899",
    "github": "https://git.com",
    "correo": "programer-js.com"
}

