GET http://localhost:3030/api/users

### test de posts
POST http://localhost:3030/api/portafolios/
Content-Type: application/json

{
    "imgUser": "https://my-cara.com",
    "skills": "muy bueno programando en javascript",
    "achievements": "Programar un api durantee 48 horas seguidas",
    "userId": 1
}
### Test enpoint put
PUT  http://localhost:3030/api/contactos/1
Content-Type: application/json

{
    "id": 1,
	"telefono": "8888899",
    "github": "https://git.com",
    "correo": "programer-js.com"
}

